seele_app/urls.py
from django.contrib import admin
from django.urls import path, include
from website.views import *
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home,name="home"),
    # path('i18n/', include('django.conf.urls.i18n')),
    path('login/',login,name="login"),
    path('signup/',signup,name="signup"),
    path('familyinfo/',familyinfo,name="familyinfo"),
    path('profile/',profile,name="profile"),
    path('delete_medical/',delete_medical,name="delete_medical"),
    path('delete_account/',delete_account,name="delete_account"),
    path('disasterprep/',disasterprep,name="disasterprep"),
    path('disasterchecklist/',disasterchecklist,name="disasterchecklist"),
    path('disasterposter/', disasterposter, name="disasterposter"),
    path('disasterposter/<int:user_id>/', disasterposter, name="disasterposter"),
    path('download/', download_poster, name='download_poster'),
    path('logout/',logout,name="logout"),
]

urlpatterns += i18n_patterns(
    path('', include('seele_app.urls_i18n')),
    path('i18n/', include('django.conf.urls.i18n')),
)

website/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=50)
    location = models.CharField(max_length=255, default='Unknown')
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    family_size = models.PositiveIntegerField(default = 1)
    medical_issues = models.TextField(blank=True, null=True)
    medication_amount = models.IntegerField(default=0)
    women_bool = models.BooleanField(default=False)
    child_bool = models.BooleanField(default=False)
    baby_bool = models.BooleanField(default=False)
    pet_bool = models.BooleanField(default=False)
    blind_bool = models.BooleanField(default=False)
    deaf_bool = models.BooleanField(default=False)
    wheelchair_bool = models.BooleanField(default=False)

website/views.py
import os
import time
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.conf import settings
from django.utils.translation import gettext as _
from django.utils.safestring import mark_safe
from django.contrib.auth.hashers import check_password, make_password
from django.contrib import messages
from django import forms
from .models import Users
import requests
import bleach
import math
from threading import Thread
from django.templatetags.static import static

ALLOWED_TAGS = ['b', 'i', 'u', 'a', 'ul', 'ol', 'li', 'p', 'br', 'strong', 'em', 'ruby', 'rt']
ALLOWED_ATTRIBUTES = {
    '*': ['class', 'id'],
    'a': ['href', 'title'],
    'ruby': ['lang'],
    'rt': []
}
def sanitize_html(content):
    return bleach.clean(content, tags=ALLOWED_TAGS, attributes=ALLOWED_ATTRIBUTES, strip=True)

APIKey = "5b3ce3597851110001cf6248f1495139fccf4eb9a4494f7bddb5a976"
from .utils import checklist_image, tts_execute

def home(request):
    context = {
        'authenticated': request.user.is_authenticated,
    }
    return render(request, 'home.html', context)

def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    if request.method == 'POST':
        try:
            email = request.POST.get('email')
            password = request.POST.get('password')
            user = Users.objects.get(email=email)
            #decrypt the password hashing
            if check_password(password, user.password):
                request.session.flush()  # Clear old session data to prevent fixation attacks
                request.session["user_email"] = email
                return redirect('profile')
            else:
                return render(request, 'login.html', {'msg': _('Enter correct password'), 'tag': 'danger'})
        except Users.DoesNotExist:
            return render(request, 'login.html', {'msg': _('Enter correct email'), 'tag': 'danger'})

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html')
    if request.method == 'POST':
        try:
            name = request.POST.get('name')
            email = request.POST.get('email')
            password = request.POST.get('password')
            confirm_password = request.POST.get('confirm_password')

            if password != confirm_password:
                return render(request, 'signup.html', {'msg': _('Passwords do not match'), 'tag': 'danger'})

            if Users.objects.filter(email=email).exists():
                return render(request, 'signup.html', {'msg': _('Email address is already associated with an account'), 'tag': 'danger'})

            if email.count('@') != 1:
                return render(request, 'signup.html', {'msg': _('Please check email'), 'tag': 'danger'})

            temp = email.split('@')
            if len(temp[0]) == 0 or len(temp[1]) == 0 or not temp[1][-3:] in ['com', 'org', 'edu']:
                return render(request, 'signup.html', {'msg': _('Please check email'), 'tag': 'danger'})

            if len(password) < 8:
                return render(request, 'signup.html', {'msg': _('Password must be at least 8 characters'), 'tag': 'danger'})

            special_chars = ['0','1','2','3','4','5','6','7','8','9','!','\"','#','$','%','&','\'','(',')','*','+',
                             ',','-','.','/',':',';','<','=','>','?','@','[',']','\\','^','_','{','|','}','~','`']

            if not any(char in special_chars for char in password):
                return render(request, 'signup.html', {'msg': _('Password must have one special character or number'), 'tag': 'danger'})

            request.session['signup_data'] = {
                'name': name,
                'email': email,
                'password': password,
            }

            return redirect('familyinfo')

        except Exception:
            return render(request, 'signup.html', {'msg': _('Error on Signup'), 'tag': 'danger'})

def familyinfo(request):
    if request.method == 'GET':
        return render(request, 'familyinfo.html')
    if request.method == 'POST':
        try:
            signup_data = request.session.get('signup_data', {})
            if not signup_data:
                return render(request, 'signup.html', {'msg': _('Please try again'), 'tag': 'danger'})

            location = request.POST.get('location')
            comma_index = location.find(',')
            latitude = location[:comma_index].strip()
            longitude = location[comma_index+1:].strip()
            family_size_str = request.POST.get('family_size')
            family_size = int(family_size_str)

            if family_size < 1 or family_size > 10:
                return render(request, 'familyinfo.html', {'msg': _('Please enter a family size between 1 and 10'), 'tag': 'danger'})

            medical_issues = request.POST.get('medical_issues', '')  # Default to empty string if not provided
            medication_amount_str = request.POST.get('medication_amount', '0')  # Default to '0' if not provided
            medication_amount = int(medication_amount_str) if medication_amount_str else 0  # Ensure it defaults to 0 if empty

            women_bool = request.POST.get('women_bool') == 'on'
            child_bool = request.POST.get('child_bool') == 'on'
            baby_bool = request.POST.get('baby_bool') == 'on'
            pet_bool = request.POST.get('pet_bool') == 'on'

            blind_bool = request.POST.get('blind_bool') == 'on'
            deaf_bool = request.POST.get('deaf_bool') == 'on'
            wheelchair_bool = request.POST.get('wheelchair_bool') == 'on'

            user = Users(
                name=signup_data['name'],
                email=signup_data['email'],
                #hashing the user's password so it isn't being stored in plaintext in the DB
                password=make_password(signup_data['password']),
                location=location,
                latitude=latitude,
                longitude=longitude,
                family_size=family_size,
                medical_issues=medical_issues,
                medication_amount=medication_amount,
                women_bool=women_bool,
                child_bool=child_bool,
                baby_bool=baby_bool,
                pet_bool=pet_bool,
                blind_bool=blind_bool,
                deaf_bool=deaf_bool,
                wheelchair_bool=wheelchair_bool,
            )
            user.save()

            # Automatically log in the user
            request.session['user_email'] = user.email
            del request.session['signup_data']
            return redirect('disasterprep')  # Redirect to disasterprep page

        except Exception as e:
            return render(request, 'familyinfo.html', {'msg': _('Error on Signup: ') + str(e), 'tag': 'danger'})

def backdoor(request):
    request.session['b_name'] = "John Smith"
    request.session['b_email'] = "TestEmail@example.com"
    request.session['b_latitude'] = 35.0
    request.session['b_longitude'] = 135.0
    request.session['b_family_size'] = 2
    request.session['b_baby_bool'] = True

    return redirect('disasterprep')

def profile(request):
    if request.method == 'GET':
        email = request.session.get("user_email")
        if not email:
            return redirect('login')

        try:
            user = Users.objects.get(email=email)
        except Users.DoesNotExist:
            return redirect('login')

        context = {
            'email': user.email,
            'name': user.name,
            'password': '',
            'longitude': user.longitude,
            'latitude': user.latitude,
            'size': user.family_size,
            'medical_issue': user.medical_issues,
            'amount': user.medication_amount,
            'women': user.women_bool,
            'child': user.child_bool,
            'baby': user.baby_bool,
            'pet': user.pet_bool,
            'blind': user.blind_bool,
            'deaf': user.deaf_bool,
            'wheelchair': user.wheelchair_bool,
        }

        return render(request, 'profile.html', context)

    if request.method == 'POST':
        email = request.session.get("user_email")
        if not email:
            return redirect('login')

        try:
            user = Users.objects.get(email=email)
        except Users.DoesNotExist:
            return redirect('login')

        # Get updated data
        name = request.POST.get('name')
        new_email = request.POST.get('email')
        password = request.POST.get('password')
        latitude = request.POST.get('latitude')
        longitude = request.POST.get('longitude')
        family_size = request.POST.get('size')
        dose = request.POST.get('dose')
        medicine = request.POST.get('medicine')
        women = request.POST.get('women')
        child = request.POST.get('child')
        baby = request.POST.get('baby')
        pet = request.POST.get('pet')
        blind = request.POST.get('blind')
        deaf = request.POST.get('deaf')
        wheelchair = request.POST.get('wheelchair')

        # Initialize context with the form data
        context = {
         'email': new_email,
         'name': name,
         'password': '',
         'longitude': longitude,
         'latitude': latitude,
         'size': family_size,
         'medical_issue': medicine if medicine != "no medicine" else '',
         'amount': dose if medicine != "no medicine" else 0,
         'women': bool(women),
         'child': bool(child),
         'baby': bool(baby),
         'pet': bool(pet),
         'blind': bool(blind),
         'deaf': bool(deaf),
         'wheelchair': bool(wheelchair),
        }

        error = False

        # Name Validation
        if name == "":
            if not error:
                messages.error(request, _('Username cannot be blank'), extra_tags='danger')
                error = True
        else:
            user.name = name

website/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="{% get_current_language as LANGUAGE_CODE %}">
{% load pwa %}
{% progressive_web_app_meta %}
<head>
    <style>
        .navbar {
            align-content: center;

        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
    <title>{% block title %}{% trans "S.E.E.L.E Home" %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fluid">
        <div class="container-fluid">
            <ul class="nav ml-auto">
                {% if request.session.user_email %}
                <!-- Display these links if user is logged in -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">{% trans "Home" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'disasterprep' %}">{% trans "Disaster Prep" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'profile' %}">{% trans "Profile" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">{% trans "Logout" %}</a>
                </li>
                {% elif request.session.b_email %}
                <!-- Display these links if user is logged in backdoor -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">{% trans "Home" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'disasterprep' %}">{% trans "Disaster Prep" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">{% trans "Logout" %}</a>
                </li>
                {% else %}
                <!-- Display these links if user is not logged in -->
                <li class="nav-item">
                    <a class="nav-link my-2 my-lg-0" href="{% url 'home' %}">{% trans "Home" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-2 my-lg-0" href="{% url 'signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link my-2 my-lg-0" href="{% url 'login' %}">{% trans "Login" %}</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <form action="{% url 'set_language' %}" method="post" class="form-inline my-2 my-lg-0">
                        {% csrf_token %}
                        <select name="language" onchange="this.form.submit()" class="form-control">
                            <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %}>English</option>
                            <option value="jp" {% if LANGUAGE_CODE == 'jp' %}selected{% endif %}>日本語</option>
                        </select>
                    </form>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        {% if messages %}
        <div class="messages">
            </div>
        </div>
        {% endif %}

        {% block content %}{% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

website/templates/csrffail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSRF Failure</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
<div class="container">
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
</div>
</body>
</html>

website/templates/delete-acct.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans "S.E.E.L.E - Settings" %}{% endblock %}
{% block content %}
<head>

</head>
<body>
<div class="delete-acct container">
    <br><br>
    <h2>{% trans "Are you sure you want to delete your account?" %}</h2>
    <div class="col mt-4">

    <div class="sad-guides row mt-6">
        <div class="col mt-2">
            <img src="{% static 'images/girl_sad.png' %}" alt="Kyodai Girl Image" class="small-image img-fluid mt-4">
        </div>
        <div class="col mt-2">
            <img src="{% static 'images/seal_sad.png' %}" alt="Seele Image" class="small-image img-fluid mt-4">
        </div>
        <div class="col mt-2">
            <img src="{% static 'images/boy_sad.png' %}" alt="Florida Boy Image" class="small-image img-fluid mt-4">
        </div>

    </div>

    </div>
    <h2>{% trans "We will miss you!" %}</h2>

    <div class="col mt-4" id="delete-acct-btns">
        <form id="delete" action="{% url 'delete_account' %}" method="POST">
        {% csrf_token %}
        <button type="submit" title="{% trans 'You will be missed!' %}" id="delete-btn" class="btn btn-danger">{% trans "Yes, delete my account" %}</button>
        </form>
        <a href="{% url 'profile' %}" title="{% trans 'Stay prepared!' %}" id="start-btn" class="btn btn-success">{% trans 'No, go back' %}</a>
    </div>

</div>
</body>


{% endblock %}

website/templates/disasterchecklist.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans "S.E.E.L.E - Checklist" %}{% endblock %}
{% block content %}
<div class="container" style="margin-top: 20px">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {% if msg %}
            <div class="alert alert-{{ tag }}">{{ msg }}</div>
            {% endif %}
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{% trans "Emergency Kit Checklist" %}</h5>
                </div>
                <div class="card-body">
                    <div class="col">
                        <div class="safety-guides row mt-6">
                            <div class="col mt-3">
                                <img src="{% static 'images/girl_safety.png' %}" alt="Safety Girl Image" id="safety-girl" class="small-image img-fluid mt-4 float-right">
                            </div>

                            <div class="col mt-3 align-self-center">
                                <p class="text-start" id="safety-msg-1"><b>{% trans "Prepare a go bag for each family member in case you must evacuate in the event of a disaster." %}</b></p>
                            </div>
                        </div>
                    </div>

                    <div class="row justify-content-center">
                        {% for category, items in categories.items %}
                        <div class="col-md-6" style="background-color: {% cycle '#ffcccc' '#ccffcc' '#ccccff' '#ffffcc' %}; margin: 5px; padding: 10px; border-radius: 5px;">
                            <h5>{{category | safe }}</h5>
                            {% if items %}
                            <ul class="list-group" style="background-color: inherit; border: none;">
                                {% for item in items %}
                                <li class="list-group-item" style="background-color: inherit; border: 1px solid #000; margin-bottom: 5px; border-radius: 4px;">
                                    <input type="checkbox" id="item{{ forloop.parentloop.counter }}{{ forloop.counter }}" name="item{{ forloop.parentloop.counter }}{{ forloop.counter }}" value="item{{ forloop.parentloop.counter }}{{ forloop.counter }}">
                                    <label for="item{{ forloop.parentloop.counter }}{{ forloop.counter }}">  {{ item|safe }}</label>
                                </li>
                                {% endfor %}
                            </ul>
                            {% else %}
                            <p>{% trans "No items available" %}</p>
                            {% endif %}
                        </div>
                        {% endfor %}

                    </div>
                    <div class="col">
                        <div class="safety-guides row mt-6">
                            <div class="col mt-3 align-self-center">
                                <p class="text-end" id="safety-msg-2"><b>{% trans "Check out all the checklist items bro! 100% preparedness only!!" %}</b></p>
                            </div>

                            <div class="col mt-3">
                                <img src="{% static 'images/boy_safety.png' %}" alt="Safety Boy Image" id="safety-boy" class="small-image img-fluid mt-4">
                            </div>
                        </div>

                    </div>
                    <div class="row justify-content-center">
                        <form action="{% url 'disasterposter' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <button type="submit" class="btn btn-success">{% trans "Generate Poster" %}</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

website/templates/disasterprep.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans "S.E.E.L.E - Preparation" %}{% endblock %}
{% block content %}
<div class="container" style="margin-top: 20px">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% if msg %}
            <div class="alert alert-{{tag}}">{{msg}}</div>
            {% endif %}
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{% trans "Disaster Prep" %}</h5>
                </div>
                <div class="card-body">
                    <form action="{% url 'disasterprep' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>{% trans "What disaster is this plan for:" %}</label>
                            <select class="form-control" name="disaster_type" id="disaster_type">
                                <option>{% trans "(None)" %}</option>
                                <option value="Typhoon">{% trans "Typhoon" %}</option>
                                <option value="Earthquake">{% trans "Earthquake" %}</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>{% trans "How will you prepare for this disaster:" %}</label>
                            <select class="form-control" name="prepare_type" id="prepare_type">
                                <option>{% trans "(None)" %}</option>
                                <option value="Evacuation Shelter">{% trans "Evacuation Shelter" %}</option>
                                <option value="Hotel">{% trans "Hotel" %}</option>
                                <option value="Stay Home">{% trans "Stay Home" %}</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success">{% trans "Generate Plan" %}</button>
                        </div>
                    </form>

                    <div class="disa-prep-img-wrapper justify-content-center">
                        <img src="{% static 'images/seal_default.png' %}" class="small-image img-fluid mt-4" id="disa-prep-img">
                        {% url 'profile' as profile_url %}
                        <p class="disa-prep-msg">
                            {% blocktrans %}Select the disaster you want to prepare for! Changes and updates to user information can be made on the <a href="{{ profile_url }}">Profile page</a>!{% endblocktrans %}
                        </p>

                   </div>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>
{% endblock %}

website/templates/familyinfo.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans "S.E.E.L.E - Information Form" %}{% endblock %}
{% block content %}
<div class="container" style="margin-top: 20px">
    <div class="col-md-4"></div>
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            {% if msg %}
            <div class="alert alert-{{tag}}">{{ msg }}</div>
            {% endif %}
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">{% trans "Family Information" %}</h5>
                </div>
                <div class="card-body">
                    <form id="family-info-form" action="{% url 'familyinfo' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label><b>{% trans "Location" %}</b></label>
                            <input type="text" placeholder="{% trans "Location " %}" class="form-control" name="location" id="location" required readonly>
                        </div>
                        <button type="button" class="btn btn-primary" id="fetch-location-btn">{% trans "Fetch Location" %}</button>
                        <div class="form-group" style="margin-top: 20px">
                            <label class="profile-info-label">{% trans "Family Household" %}</label>
                            <input type="text" placeholder="{% trans "Number of Family Members" %}" class="form-control" name="family_size" required>
                        </div>
                        {{ form.as_p }}
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="id_women_bool" name="women_bool">
                            <label class="form-check-label" for="id_women_bool">{% trans "There are women in my family." %}</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="id_child_bool" name="child_bool">
                            <label class="form-check-label" for="id_child_bool">{% trans "There are children in my family." %}</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="id_baby_bool" name="baby_bool">
                            <label class="form-check-label" for="id_baby_bool">{% trans "There are infants in my family." %}</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="id_pet_bool" name="pet_bool">
                            <label class="form-check-label" for="id_pet_bool">{% trans "There are pets in my family." %}</label>
                        </div>
                        <label class="profile-info-label">{% trans "Applicable disabilities/conditions" %}</label>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="id_blind_bool" name="blind_bool">
                            <label class="form-check-label" for="id_blind_bool">{% trans "Blind or poor vision" %}</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="id_deaf_bool" name="deaf_bool">
                            <label class="form-check-label" for="id_deaf_bool">{% trans "Deaf or hard of hearing" %}</label>
                        </div>
                        <div class="form-group form-check">
                            <input type="checkbox" class="form-check-input" id="id_wheelchair_bool" name="wheelchair_bool">
                            <label class="form-check-label" for="id_wheelchair_bool">{% trans "Mobility impairment" %}</label>
                        </div>
                        <div class="form-group">
                            <label><b>{% trans "Medical Issues (optional):" %}</b></label>
                            <input type="text" placeholder="{% trans "Enter medical condition" %}" class="form-control" name="medical_issues">
                        </div>
                        <div class="form-group">
                            <label><b>{% trans "Medication Amount (optional):" %}</b></label>
                            <input type="number" class="form-control" name="medication_amount" placeholder="{% trans "Amount of medication needed per day" %}">
                        </div>


                        <div class="form-group">
                            <button type="submit" class="btn btn-success" id="submit-btn" disabled>{% trans "Continue" %}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        var fetchLocationBtn = document.getElementById('fetch-location-btn');
        var submitBtn = document.getElementById('submit-btn');
        var locationInput = document.getElementById('location');

        fetchLocationBtn.addEventListener('click', function() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(function(position) {
                    var lat = position.coords.latitude;
                    var lon = position.coords.longitude;
                    locationInput.value = lat + "," + lon;
                    submitBtn.disabled = false;
                }, function(error) {
                    console.error("Error occurred while retrieving location: ", error);
                });
            } else {
                console.error("Geolocation is not supported by this browser.");
            }
        });
    });
</script>

{% endblock %}